[project]
name = "normbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pycryptodome>=3.23.0",
    "pydantic>=2.12.5",
    "python-telegram-bot>=22.6",
]
